### ISSUE TITLE
Contributors guide?

### ISSUE THREAD

**Issue by azilnik** [raunofreiberg/ui-playbook#13]
Are you looking for help? You might want to make a guide about what you're looking for help with.

**Comment by raunofreiberg** [comment]
Hey,

Contributions are definitely welcome. Unfortunately, I haven't _yet_ set up a proper contributing guide or roadmap since I've just sort of been coming up with content on the go.

It's on my todo list, so I'll try to address both of those ASAP! Meanwhile, feel free to extend (or correct) the existing components with additional examples or information.

**Comment by raunofreiberg** [comment]
@azilnik I set up a [contributing document](https://github.com/raunofreiberg/ui-playbook/blob/master/CONTRIBUTING.md) along with an issue template that should make it easier to propose new plays. 

Also, wrote down a list of components that I think could be covered: https://github.com/raunofreiberg/ui-playbook/issues/17

Does this help? 🙂

**Comment by raunofreiberg** [comment]
I'm closing this for now. Feel free to reopen if you have additional ideas!
